In [2]:
import numpy as np

# Funkcja do tworzenia sekwencji
def create_sequences(data, seq_length):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i + seq_length])
        y.append(data[i + seq_length])
    return np.array(X), np.array(y)

seq_length = 5
data = np.array([i for i in range(1, 101)])
X, y = create_sequences(data, seq_length)
print(X)
print(y)

[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]
 [ 7  8  9 10 11]
 [ 8  9 10 11 12]
 [ 9 10 11 12 13]
 [10 11 12 13 14]
 [11 12 13 14 15]
 [12 13 14 15 16]
 [13 14 15 16 17]
 [14 15 16 17 18]
 [15 16 17 18 19]
 [16 17 18 19 20]
 [17 18 19 20 21]
 [18 19 20 21 22]
 [19 20 21 22 23]
 [20 21 22 23 24]
 [21 22 23 24 25]
 [22 23 24 25 26]
 [23 24 25 26 27]
 [24 25 26 27 28]
 [25 26 27 28 29]
 [26 27 28 29 30]
 [27 28 29 30 31]
 [28 29 30 31 32]
 [29 30 31 32 33]
 [30 31 32 33 34]
 [31 32 33 34 35]
 [32 33 34 35 36]
 [33 34 35 36 37]
 [34 35 36 37 38]
 [35 36 37 38 39]
 [36 37 38 39 40]
 [37 38 39 40 41]
 [38 39 40 41 42]
 [39 40 41 42 43]
 [40 41 42 43 44]
 [41 42 43 44 45]
 [42 43 44 45 46]
 [43 44 45 46 47]
 [44 45 46 47 48]
 [45 46 47 48 49]
 [46 47 48 49 50]
 [47 48 49 50 51]
 [48 49 50 51 52]
 [49 50 51 52 53]
 [50 51 52 53 54]
 [51 52 53 54 55]
 [52 53 54 55 56]
 [53 54 55 56 57]
 [54 55 56 57 58]
 [55 56 57 58 59]
 [56 57 58